### ISSUE TITLE
Use modules, like other highlighters

### ISSUE THREAD

**Issue by jamiesyme** [ABuffSeagull/kakoune-vue#3]
If you look at something like `html.kak` in a recent release of Kakoune ([see here](https://github.com/mawww/kakoune/blob/master/rc/filetype/html.kak)), the `provide-module html %[ ... ]` command is used to wrap highlighters and commands.

Functionality like this would make it easier for users to solve issue #2 themselves (ie. wait until the `vue` module is loaded, then use `require-module` for whatever modules you may use).

**Comment by brynedwards** [comment]
Hi, as this hasn't been updated since Kakoune added the module commands I had a go at it, it works for me: https://gist.github.com/brynedwards/4fe62e968d905f6034cd456472cd0c84

**Comment by ABuffSeagull** [comment]
Yeah, sorry about the radio silence. Just got a new job and been too beat every night to update this. I should be able to look at it tonight or this weekend though.

**Comment by ABuffSeagull** [comment]
Okay, *finally* updated it. Sorry again for the absurd delay, and thank you so much @brynedwards for your gist, I basically just stole all your code, minus the prettier stuff :laughing:
